// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "user_interface.hpp"

Fl_Menu_Item UserInterface::menu_menu_color_map[] = {
 {"Black and white", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Rainbow", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Red to white", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::option_black_white = UserInterface::menu_menu_color_map + 0;
Fl_Menu_Item* UserInterface::option_rainbow = UserInterface::menu_menu_color_map + 1;
Fl_Menu_Item* UserInterface::option_red_white = UserInterface::menu_menu_color_map + 2;

Fl_Menu_Item UserInterface::menu_menu_scalar_choice[] = {
 {"Smoke", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Velocity ||v||", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Force ||f||", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::option_scalar_smoke = UserInterface::menu_menu_scalar_choice + 0;
Fl_Menu_Item* UserInterface::option_scalar_velocity = UserInterface::menu_menu_scalar_choice + 1;
Fl_Menu_Item* UserInterface::option_scalar_force = UserInterface::menu_menu_scalar_choice + 2;

Fl_Menu_Item UserInterface::menu_menu_vector_choice[] = {
 {"Velocity", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Force", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Smoke gradient", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Velocity gradient", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::option_vector_velocity = UserInterface::menu_menu_vector_choice + 0;
Fl_Menu_Item* UserInterface::option_vector_force = UserInterface::menu_menu_vector_choice + 1;
Fl_Menu_Item* UserInterface::option_vector_gradient_smoke = UserInterface::menu_menu_vector_choice + 2;
Fl_Menu_Item* UserInterface::option_vector_gradient_velocity = UserInterface::menu_menu_vector_choice + 3;

Fl_Menu_Item UserInterface::menu_menu_vector_shape[] = {
 {"Hedgehog", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Cone", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2D arrow", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::option_hedgehog = UserInterface::menu_menu_vector_shape + 0;
Fl_Menu_Item* UserInterface::option_cone = UserInterface::menu_menu_vector_shape + 1;
Fl_Menu_Item* UserInterface::option_arrow_2d = UserInterface::menu_menu_vector_shape + 2;

Fl_Double_Window* UserInterface::make_window() {
  { main_window = new Fl_Double_Window(1650, 1000, "Smoke");
    main_window->user_data((void*)(this));
    { gl_window = new GlWindow(0, 0, 1000, 1000);
      gl_window->box(FL_NO_BOX);
      gl_window->color(FL_BACKGROUND_COLOR);
      gl_window->selection_color(FL_BACKGROUND_COLOR);
      gl_window->labeltype(FL_NO_LABEL);
      gl_window->labelfont(0);
      gl_window->labelsize(14);
      gl_window->labelcolor(FL_FOREGROUND_COLOR);
      gl_window->align(Fl_Align(FL_ALIGN_CENTER));
      gl_window->when(FL_WHEN_RELEASE);
    } // GlWindow* gl_window
    { separator = new Fl_Box(1000, 0, 10, 1000, "separator");
      separator->box(FL_FLAT_BOX);
      separator->color((Fl_Color)44);
      separator->labeltype(FL_NO_LABEL);
    } // Fl_Box* separator
    { color_bar = new ColorBar(1010, 70, 40, 800);
      color_bar->box(FL_ENGRAVED_BOX);
      color_bar->color(FL_BACKGROUND_COLOR);
      color_bar->selection_color(FL_BACKGROUND_COLOR);
      color_bar->labeltype(FL_NORMAL_LABEL);
      color_bar->labelfont(0);
      color_bar->labelsize(14);
      color_bar->labelcolor(FL_FOREGROUND_COLOR);
      color_bar->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      color_bar->when(FL_WHEN_RELEASE);
    } // ColorBar* color_bar
    { output_color_bar_max_val = new Fl_Value_Output(1050, 55, 70, 30);
    } // Fl_Value_Output* output_color_bar_max_val
    { output_color_bar_med_val = new Fl_Value_Output(1050, 455, 70, 30);
    } // Fl_Value_Output* output_color_bar_med_val
    { output_color_bar_min_val = new Fl_Value_Output(1050, 855, 70, 30);
    } // Fl_Value_Output* output_color_bar_min_val
    { text_toggle = new Fl_Box(1135, 50, 200, 20, "Toggle");
      text_toggle->labelfont(1);
    } // Fl_Box* text_toggle
    { toggle_draw_smoke = new Fl_Light_Button(1135, 90, 200, 20, "Toggle smoke");
    } // Fl_Light_Button* toggle_draw_smoke
    { toggle_draw_vecs = new Fl_Light_Button(1135, 110, 200, 20, "Toggle vectors");
      toggle_draw_vecs->value(1);
    } // Fl_Light_Button* toggle_draw_vecs
    { toggle_frozen = new Fl_Light_Button(1135, 70, 200, 20, "Toggle play");
    } // Fl_Light_Button* toggle_frozen
    { toggle_vector_color = new Fl_Light_Button(1135, 130, 200, 20, "Toggle vector coloring");
    } // Fl_Light_Button* toggle_vector_color
    { text_scalar_col = new Fl_Box(1135, 170, 200, 20, "Color mapping");
      text_scalar_col->labelfont(1);
    } // Fl_Box* text_scalar_col
    { toggle_parametrize_color_map = new Fl_Light_Button(1135, 190, 200, 20, "Parametrize color map");
    } // Fl_Light_Button* toggle_parametrize_color_map
    { counter_num_bands = new Fl_Counter(1135, 227, 200, 21, "Number of bands");
      counter_num_bands->align(Fl_Align(FL_ALIGN_TOP));
      counter_num_bands->step(1, 10);
      counter_num_bands->value(Config::num_bands);
      counter_num_bands->bounds(2,256);
    } // Fl_Counter* counter_num_bands
    { Fl_Box* o = new Fl_Box(1135, 265, 200, 17, "Clamp or scale value?");
      o->labelfont(1);
    } // Fl_Box* o
    { button_clamp = new Fl_Button(1135, 280, 100, 20, "Clamp");
    } // Fl_Button* button_clamp
    { button_scale = new Fl_Button(1235, 280, 100, 20, "Scale");
      button_scale->color(FL_GREEN);
      button_scale->deactivate();
    } // Fl_Button* button_scale
    { value_clamp_min = new Fl_Value_Input(1187, 300, 48, 25, "min:");
      value_clamp_min->hide();
    } // Fl_Value_Input* value_clamp_min
    { value_clamp_max = new Fl_Value_Input(1287, 300, 48, 25, "max:");
      value_clamp_max->value(1);
      value_clamp_max->hide();
    } // Fl_Value_Input* value_clamp_max
    { menu_color_map = new Fl_Choice(1135, 245, 200, 20);
      menu_color_map->down_box(FL_BORDER_BOX);
      menu_color_map->menu(menu_menu_color_map);
    } // Fl_Choice* menu_color_map
    { text_increase_decrease = new Fl_Box(1135, 350, 200, 16, "Increase/decrease values");
      text_increase_decrease->labelfont(1);
    } // Fl_Box* text_increase_decrease
    { counter_time_step = new Fl_Counter(1135, 384, 200, 21, "Time step");
      counter_time_step->align(Fl_Align(FL_ALIGN_TOP));
      counter_time_step->step(0.001, 0.01);
      counter_time_step->value(Config::time_step);
      counter_time_step->bounds(0.001,1);
    } // Fl_Counter* counter_time_step
    { counter_visc = new Fl_Counter(1135, 424, 200, 21, "Viscosity");
      counter_visc->type(1);
      counter_visc->align(Fl_Align(FL_ALIGN_TOP));
      counter_visc->value(Config::visc);
      counter_visc->step(0.00025);
      counter_visc->bounds(0.0001,0.02);
    } // Fl_Counter* counter_visc
    { counter_vec_scale = new Fl_Counter(1135, 464, 200, 21, "Vector scaling");
      counter_vec_scale->type(1);
      counter_vec_scale->align(Fl_Align(FL_ALIGN_TOP));
      counter_vec_scale->value(Config::vec_scale);
      counter_vec_scale->step(200);
    } // Fl_Counter* counter_vec_scale
    { counter_num_glyphs = new Fl_Counter(1135, 504, 200, 21, "Number of glyphs");
      counter_num_glyphs->align(Fl_Align(FL_ALIGN_TOP));
      counter_num_glyphs->step(1, 10);
      counter_num_glyphs->value(Config::num_glyphs);
    } // Fl_Counter* counter_num_glyphs
    { Fl_Box* o = new Fl_Box(1385, 50, 200, 20, "Datasets");
      o->labelfont(1);
    } // Fl_Box* o
    { menu_scalar_choice = new Fl_Choice(1435, 70, 150, 20, "Scalar:");
      menu_scalar_choice->down_box(FL_BORDER_BOX);
      menu_scalar_choice->menu(menu_menu_scalar_choice);
    } // Fl_Choice* menu_scalar_choice
    { menu_vector_choice = new Fl_Choice(1435, 90, 150, 20, "Vector:");
      menu_vector_choice->down_box(FL_BORDER_BOX);
      menu_vector_choice->menu(menu_menu_vector_choice);
    } // Fl_Choice* menu_vector_choice
    { text_vector_shape = new Fl_Box(1385, 130, 200, 17, "Vector shape");
      text_vector_shape->labelfont(1);
    } // Fl_Box* text_vector_shape
    { menu_vector_shape = new Fl_Choice(1435, 145, 150, 20, "choice:");
      menu_vector_shape->down_box(FL_BORDER_BOX);
      menu_vector_shape->menu(menu_menu_vector_shape);
    } // Fl_Choice* menu_vector_shape
    main_window->end();
  } // Fl_Double_Window* main_window
  return main_window;
}

void UserInterface::show() {
  main_window->show();
}
