// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef user_interface_hpp
#define user_interface_hpp
#include <FL/Fl.H>
class GlWindow; class ColorBar; class Controller;
#include <FL/Fl_Double_Window.H>
#include "config.hpp"
#include <iostream>
#include "gl_window.hpp"
#include <FL/Fl_Box.H>
#include "color_bar.hpp"
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Choice.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *main_window;
  GlWindow *gl_window;
  Fl_Box *separator;
  ColorBar *color_bar;
  Fl_Box *text_toggle;
  Fl_Button *toggle_dir_color;
  Fl_Button *toggle_draw_smoke;
  Fl_Button *toggle_draw_vecs;
  Fl_Button *toggle_frozen;
  Fl_Box *text_scalar_col;
  Fl_Light_Button *toggle_parametrize_color_map;
  Fl_Counter *counter_num_bands;
  Fl_Button *button_clamp;
  Fl_Button *button_scale;
  Fl_Value_Input *value_clamp_min;
  Fl_Value_Input *value_clamp_max;
  Fl_Choice *menu_color_map;
  static Fl_Menu_Item menu_menu_color_map[];
  static Fl_Menu_Item *option_black_white;
  static Fl_Menu_Item *option_rainbow;
  static Fl_Menu_Item *option_red_white;
  Fl_Box *text_increase_decrease;
  Fl_Counter *counter_time_step;
  Fl_Counter *counter_visc;
  Fl_Counter *counter_vec_scale;
  Fl_Counter *counter_num_glyphs;
  void show();
};
#endif
